[workspace]
authors = ["Thomas A Caswell <tcaswell@bnl.gov>"]
channels = ["conda-forge"]
name = "Lab6_testdata_share"
platforms = ["linux-64", "win-64", "osx-arm64"]
version = "0.1.0"

[environments]
prek = { features = ["prek"], solve-group = "prek", no-default-feature = true }
test = { features = ["test"], solve-group = "default" }
default = { solve-group = "default" }

[dependencies]
matplotlib = ">=3.10.8,<4"
ipython = ">=9.12.0,<10"
numpy = ">=2.4.3,<3"
h5py = ">=3.16.0,<4"
hdf5-external-filter-plugins-lz4 = ">=0.1.0,<0.2"
hdf5-external-filter-plugins-bitshuffle = ">=0.1.0,<0.2"
scikit-image = ">=0.26.0,<0.27"
tqdm = ">=4.67.3,<5"
python = ">=3.14.3,<3.15"
pyyaml = ">=6.0.3,<7"
pytest = ">=9.0.2,<10"
hdf5plugin = ">=6.0.0,<7"
sparse = ">=0.18.0,<0.19"
pyarrow = ">=23.0.1,<24"
git = ">=2.53.0,<3"

[feature.prek.dependencies]
prek = ">=0.3.8,<0.4"

[feature.prek.tasks]
prek = "prek run --all-files"

[feature.test.dependencies]
pytest = ">=9.0.2,<10"
pytest-cov = ">=7.1.0,<8"

[feature.test.tasks]
test = "pytest"

[pypi-dependencies]
multihead = { path = ".", editable = true }
